### ISSUE TITLE
Blank email on Register page

### ISSUE THREAD

**Issue by elise-wildflower** [Tomuke-H/dpl-overflow#69]
Summary:  When the email input is left blank on the registration page this error pops up: "Account already exists. Please log in"

Steps to Reproduce:  Click on "get started".  Leave the email portion of the form blank and click the register button.

Expected Result:  An error that tells the user to enter an email address

Actual Result: Error says that account already exists

Source URL: https://dpl-overflow.herokuapp.com/register

![Screen Shot 2021-10-22 at 11 18 13 AM](https://user-images.githubusercontent.com/82512878/138496824-f08d19de-6533-4e52-8975-2a5dc485325c.png)

**Comment by mjsivertsen** [comment]
Better errors for blank fields, unmatching passwords, etc. in login and register pages.  Cleared out auto-states for email, password, and key.
